import numpy as np
import cv2
A = np.array([1, 2, 3])
print(np.power(A,2))
print(A)
print("==================")
A = np.double(A)
print(A)
print("==================")
out = np.zeros(A.shape, np.double)
normalized = cv2.normalize(A, out, 1.0, 0.0, cv2.NORM_MINMAX)
print(out)
print("==================")
print(normalized)
print("==================")